from app.db.session import Base, SessionLocal, engine
from app.models.scheme import Scheme

NSFDC = "https://nsfdc.nic.in/faqs"
NSTFDC = "https://nstfdc.tribal.gov.in"
NBCFDC = "https://nbcfdc.gov.in"
NMDFC = "https://nmdfc.org"
PMEGP_URL = "https://kviconline.gov.in/pmegpeportal"
PM_VISHWAKARMA_URL = "https://pmvishwakarma.gov.in"
STANDUP_URL = "https://www.standupmitra.in"
MUDRA_URL = "https://www.mudra.org.in"

SCHEMES = [
    {
        "code": "NSFDC-MFS",
        "name": "Micro Finance Scheme (MFS)",
        "provider": "National Scheduled Castes Finance and Development Corporation (NSFDC)",
        "description": "Micro-credit for small business activities for SC entrepreneurs with project cost up to ₹1.40 lakh.",
        "beneficiary_category": "SC",
        "min_project_cost": None,
        "max_project_cost": 140000,
        "max_loan_amount": 125000,
        "beneficiary_interest_rate": 6.5,
        "repayment_years": 3,
        "moratorium_months": 3,
        "channel_partners": ["State Channelizing Agencies (SCAs)", "Other Channelizing Agencies (CAs)"],
        "purposes": ["small business", "micro enterprise", "retail", "income generating activity"],
        "required_documents": ["Caste Certificate (SC)", "Income Proof (Family <= 5L)", "Aadhaar Card & PAN", "Bank Account Details", "Project Cost Quotation"],
        "eligibility_rules": ["SC community member", "Annual family income <= ₹5,00,000", "Project cost <= ₹1,40,000"],
        "source_url": NSFDC,
        "active": True,
    },
    {
        "code": "NSFDC-AMY",
        "name": "Aajeevika Micro-Finance Yojana (AMY)",
        "provider": "National Scheduled Castes Finance and Development Corporation (NSFDC)",
        "description": "Prompt micro-finance through selected NBFC-MFIs for SC entrepreneurs up to ₹1.40 lakh.",
        "beneficiary_category": "SC",
        "min_project_cost": None,
        "max_project_cost": 140000,
        "max_loan_amount": 125000,
        "beneficiary_interest_rate": 15.0,
        "repayment_years": 3,
        "moratorium_months": 3,
        "channel_partners": ["Selected NBFC-MFIs", "Microfinance Institutions"],
        "purposes": ["micro finance", "small business", "trading", "income generating activity"],
        "required_documents": ["Caste Certificate (SC)", "Income Proof", "KYC Documents", "MFI Membership Card"],
        "eligibility_rules": ["SC community member", "Annual family income <= ₹5,00,000", "Project cost <= ₹1,40,000"],
        "source_url": NSFDC,
        "active": True,
    },
    {
        "code": "NSFDC-TL",
        "name": "NSFDC Term Loan Scheme",
        "provider": "National Scheduled Castes Finance and Development Corporation (NSFDC)",
        "description": "Concessional financing for larger income-generating projects above ₹1.40 lakh up to ₹50 lakh.",
        "beneficiary_category": "SC",
        "min_project_cost": 140000,
        "max_project_cost": 5000000,
        "max_loan_amount": 4500000,
        "beneficiary_interest_rate": 8.0,
        "repayment_years": 7,
        "moratorium_months": 6,
        "channel_partners": ["State Channelizing Agencies (SCAs)", "Regional Rural Banks (RRBs)", "Public Sector Banks"],
        "purposes": ["agriculture", "dairy", "poultry", "manufacturing", "handicrafts", "boutique", "retail", "repair", "transport", "commercial vehicle", "e-rickshaw", "service business"],
        "required_documents": ["Caste Certificate (SC)", "Income Certificate (Family <= 5L)", "Detailed Project Report (DPR)", "Land/Premises Lease", "KYC Proofs"],
        "eligibility_rules": ["SC community member", "Annual family income <= ₹5,00,000", "Project cost > ₹1,40,000 and <= ₹50,00,000"],
        "source_url": NSFDC,
        "active": True,
    },
    {
        "code": "NSFDC-UNY",
        "name": "Udyam Nidhi Yojana (UNY)",
        "provider": "National Scheduled Castes Finance and Development Corporation (NSFDC)",
        "description": "Financing for small/micro enterprise activities with project cost up to ₹5 lakh.",
        "beneficiary_category": "SC",
        "min_project_cost": None,
        "max_project_cost": 500000,
        "max_loan_amount": 450000,
        "beneficiary_interest_rate": 13.0,
        "repayment_years": 5,
        "moratorium_months": 3,
        "channel_partners": ["Cooperative Societies", "Cooperative Banks", "Small Finance Banks"],
        "purposes": ["small business", "micro enterprise", "repair shop", "service business"],
        "required_documents": ["Caste Certificate (SC)", "Income Proof", "KYC Documents", "Cooperative Society Membership"],
        "eligibility_rules": ["SC community member", "Annual family income <= ₹5,00,000", "Project cost <= ₹5,00,000"],
        "source_url": NSFDC,
        "active": True,
    },
    {
        "code": "NSFDC-MSY",
        "name": "Mahila Samriddhi Yojana (MSY)",
        "provider": "National Scheduled Castes Finance and Development Corporation (NSFDC)",
        "description": "Dedicated micro-credit scheme empowering SC women entrepreneurs with highly subsidized loans up to ₹1.40 lakh.",
        "beneficiary_category": "SC",
        "min_project_cost": None,
        "max_project_cost": 140000,
        "max_loan_amount": 125000,
        "beneficiary_interest_rate": 4.0,
        "repayment_years": 3,
        "moratorium_months": 3,
        "channel_partners": ["State Channelizing Agencies (SCAs)", "Women Development Corporations"],
        "purposes": ["women entrepreneurship", "tailoring", "beauty parlor", "handicrafts", "grocery", "micro enterprise"],
        "required_documents": ["Caste Certificate (SC)", "Income Proof (Family <= 5L)", "Aadhaar Card", "Women Self-Declaration", "Bank Account Details"],
        "eligibility_rules": ["SC female entrepreneur", "Annual family income <= ₹5,00,000", "Project cost <= ₹1,40,000"],
        "source_url": NSFDC,
        "active": True,
    },
    {
        "code": "NSFDC-GBS",
        "name": "Green Business Scheme (GBS)",
        "provider": "National Scheduled Castes Finance and Development Corporation (NSFDC)",
        "description": "Financial assistance for SC entrepreneurs setting up eco-friendly green businesses (e-vehicles, solar, bio-gas, recycling).",
        "beneficiary_category": "SC",
        "min_project_cost": 100000,
        "max_project_cost": 3000000,
        "max_loan_amount": 2700000,
        "beneficiary_interest_rate": 6.0,
        "repayment_years": 7,
        "moratorium_months": 6,
        "channel_partners": ["SCAs", "State Renewable Energy Agencies", "Public Sector Banks"],
        "purposes": ["green business", "e-rickshaw", "solar power", "bio-gas", "waste management", "organic farming"],
        "required_documents": ["Caste Certificate (SC)", "Income Certificate", "Green Business Technical Quotation", "DPR", "KYC"],
        "eligibility_rules": ["SC community member", "Annual family income <= ₹5,00,000", "Project cost <= ₹30,00,000", "Eco-friendly activity"],
        "source_url": NSFDC,
        "active": True,
    },
    {
        "code": "NSTFDC-TL",
        "name": "NSTFDC Term Loan Scheme",
        "provider": "National Scheduled Tribes Finance and Development Corporation (NSTFDC)",
        "description": "Term Loan scheme for Scheduled Tribe (ST) entrepreneurs for viable income-generating projects up to ₹50 lakh.",
        "beneficiary_category": "ST",
        "min_project_cost": 50000,
        "max_project_cost": 5000000,
        "max_loan_amount": 4500000,
        "beneficiary_interest_rate": 6.0,
        "repayment_years": 10,
        "moratorium_months": 12,
        "channel_partners": ["State Tribal Development Corporations", "Public Sector Banks", "RRBs"],
        "purposes": ["agriculture", "forest produce", "handicrafts", "transport", "manufacturing", "tourism", "retail"],
        "required_documents": ["ST Tribe Certificate", "Income Certificate", "Project Report", "Aadhaar Card", "Bank Account Details"],
        "eligibility_rules": ["ST community member", "Annual family income <= ₹3,00,000", "Project cost <= ₹50,00,000"],
        "source_url": NSTFDC,
        "active": True,
    },
    {
        "code": "NSTFDC-AMES",
        "name": "Adivasi Mahila Sashaktikaran Yojana (AMES)",
        "provider": "National Scheduled Tribes Finance and Development Corporation (NSTFDC)",
        "description": "Exclusive concessional financial assistance for ST women entrepreneurs for unit cost up to ₹2.00 lakh at 4% interest.",
        "beneficiary_category": "ST",
        "min_project_cost": None,
        "max_project_cost": 200000,
        "max_loan_amount": 180000,
        "beneficiary_interest_rate": 4.0,
        "repayment_years": 5,
        "moratorium_months": 6,
        "channel_partners": ["State Tribal Channelizing Agencies", "ST Women Cooperatives"],
        "purposes": ["tribal handicrafts", "minor forest produce", "poultry", "weaving", "small shop", "women enterprise"],
        "required_documents": ["ST Tribe Certificate", "Income Certificate", "Aadhaar Card", "Bank Passbook"],
        "eligibility_rules": ["ST female entrepreneur", "Annual family income <= ₹3,00,000", "Project cost <= ₹2,00,000"],
        "source_url": NSTFDC,
        "active": True,
    },
    {
        "code": "NBCFDC-GLS",
        "name": "NBCFDC General Loan Scheme for OBCs",
        "provider": "National Backward Classes Finance and Development Corporation (NBCFDC)",
        "description": "Concessional term loans for members of Other Backward Classes (OBCs) for projects up to ₹15 lakh.",
        "beneficiary_category": "OBC",
        "min_project_cost": 50000,
        "max_project_cost": 1500000,
        "max_loan_amount": 1250000,
        "beneficiary_interest_rate": 7.0,
        "repayment_years": 8,
        "moratorium_months": 6,
        "channel_partners": ["State Backward Classes Development Corporations", "Regional Rural Banks"],
        "purposes": ["small scale industry", "service sector", "transport", "agriculture", "artisan activity"],
        "required_documents": ["OBC Non-Creamy Layer Certificate", "Income Certificate (Family <= 3L)", "Project Proposal", "KYC Documents"],
        "eligibility_rules": ["OBC community (Non-Creamy Layer)", "Annual family income <= ₹3,00,000", "Project cost <= ₹15,00,000"],
        "source_url": NBCFDC,
        "active": True,
    },
    {
        "code": "NBCFDC-SWARNIMA",
        "name": "New Swarnima Scheme for OBC Women",
        "provider": "National Backward Classes Finance and Development Corporation (NBCFDC)",
        "description": "Concessional financial assistance for OBC female entrepreneurs up to ₹2.00 lakh at 5% interest per annum.",
        "beneficiary_category": "OBC",
        "min_project_cost": None,
        "max_project_cost": 200000,
        "max_loan_amount": 200000,
        "beneficiary_interest_rate": 5.0,
        "repayment_years": 8,
        "moratorium_months": 6,
        "channel_partners": ["State Backward Classes Channelizing Agencies"],
        "purposes": ["women enterprise", "tailoring", "food processing", "handicrafts", "beauty parlour", "dairy"],
        "required_documents": ["OBC Non-Creamy Layer Certificate", "Income Certificate (Family <= 3L)", "Aadhaar Card", "Bank Details"],
        "eligibility_rules": ["OBC female entrepreneur", "Annual family income <= ₹3,00,000", "Project cost <= ₹2,00,000"],
        "source_url": NBCFDC,
        "active": True,
    },
    {
        "code": "NMDFC-TL",
        "name": "NMDFC Term Loan for Minority Entrepreneurs",
        "provider": "National Minorities Development and Finance Corporation (NMDFC)",
        "description": "Concessional financial assistance for notified Minorities (Muslims, Christians, Sikhs, Buddhists, Parsis, Jains) up to ₹30 lakh.",
        "beneficiary_category": "Minority",
        "min_project_cost": 50000,
        "max_project_cost": 3000000,
        "max_loan_amount": 2500000,
        "beneficiary_interest_rate": 6.0,
        "repayment_years": 5,
        "moratorium_months": 6,
        "channel_partners": ["State Minority Financial Corporations", "Scheduled Commercial Banks"],
        "purposes": ["manufacturing", "trade", "service sector", "transport", "crafts", "small business"],
        "required_documents": ["Minority Community Certificate / Self-Declaration", "Income Proof (Family <= 3L)", "DPR", "KYC"],
        "eligibility_rules": ["Notified Minority community member", "Annual family income <= ₹3,00,000", "Project cost <= ₹30,00,000"],
        "source_url": NMDFC,
        "active": True,
    },
    {
        "code": "NMDFC-VIRASAT",
        "name": "Virasat Scheme for Minority Artisans",
        "provider": "National Minorities Development and Finance Corporation (NMDFC)",
        "description": "Specialized credit scheme to preserve traditional arts and crafts for minority artisans up to ₹10 lakh at 4%-5% interest.",
        "beneficiary_category": "Minority",
        "min_project_cost": None,
        "max_project_cost": 1000000,
        "max_loan_amount": 900000,
        "beneficiary_interest_rate": 4.5,
        "repayment_years": 5,
        "moratorium_months": 6,
        "channel_partners": ["State Minority Channelizing Agencies", "Artisan Associations"],
        "purposes": ["traditional crafts", "handloom", "woodwork", "embroidery", "metalcraft", "pottery"],
        "required_documents": ["Minority Certificate", "Artisan Identity Card / Pehchan Card", "Income Proof", "Bank Details"],
        "eligibility_rules": ["Minority community artisan", "Annual family income <= ₹3,00,000", "Project cost <= ₹10,00,000"],
        "source_url": NMDFC,
        "active": True,
    },
    {
        "code": "PMEGP",
        "name": "Prime Minister's Employment Generation Programme (PMEGP)",
        "provider": "Khadi and Village Industries Commission (KVIC) / Ministry of MSME",
        "description": "Credit-linked capital subsidy scheme providing up to 35% government subsidy for setting up new micro-enterprises.",
        "beneficiary_category": "General", # Eligible for SC/ST/OBC/Women/Minority/PwD with special 35% subsidy
        "min_project_cost": 100000,
        "max_project_cost": 5000000,
        "max_loan_amount": 4750000,
        "beneficiary_interest_rate": 8.5,
        "repayment_years": 7,
        "moratorium_months": 6,
        "channel_partners": ["KVIC", "KVIB", "District Industries Centre (DIC)", "Scheduled Commercial Banks"],
        "purposes": ["manufacturing", "food processing", "textile", "services", "woodwork", "repair shop", "rural enterprise"],
        "required_documents": ["Aadhaar Card", "Caste/Special Category Certificate (for 35% Subsidy)", "EDP Training Certificate", "Detailed Project Report (DPR)", "Highest Qualification (8th pass for >10L Mfg)"],
        "eligibility_rules": ["Age >= 18 years", "New greenfield project", "No family income ceiling restriction", "35% subsidy for SC/ST/OBC/Women/Minorities/Rural"],
        "source_url": PMEGP_URL,
        "active": True,
    },
    {
        "code": "PM-VISHWAKARMA",
        "name": "PM Vishwakarma Scheme",
        "provider": "Ministry of Micro, Small and Medium Enterprises (MSME)",
        "description": "Holistic support for 18 traditional artisan trades with 5% interest collateral-free loan up to ₹3 lakh, ₹15,000 toolkit voucher, and daily training stipend.",
        "beneficiary_category": "General",
        "min_project_cost": None,
        "max_project_cost": 300000,
        "max_loan_amount": 300000,
        "beneficiary_interest_rate": 5.0,
        "repayment_years": 3,
        "moratorium_months": 1,
        "channel_partners": ["Common Service Centres (CSCs)", "Gram Panchayats", "Public Sector Banks"],
        "purposes": ["carpenter", "boat maker", "armorer", "blacksmith", "hammer & toolkit maker", "locksmith", "goldsmith", "potter", "sculptor", "cobbler", "mason", "basket weaver", "doll & toy maker", "barber", "garland maker", "washerman", "tailor", "fishing net maker"],
        "required_documents": ["Aadhaar Card", "Ration Card", "Bank Account Details", "Trade Skill Self-Declaration"],
        "eligibility_rules": ["Practicing one of 18 traditional Vishwakarma trades", "Age >= 18 years", "Only one member per family"],
        "source_url": PM_VISHWAKARMA_URL,
        "active": True,
    },
    {
        "code": "STANDUP-INDIA",
        "name": "Stand-Up India Scheme",
        "provider": "Department of Financial Services / Small Industries Development Bank of India (SIDBI)",
        "description": "Bank loans between ₹10 lakh and ₹1 Crore to SC, ST, and Women borrowers for establishing greenfield manufacturing, service, or trading enterprises.",
        "beneficiary_category": "General", # Explicitly SC/ST and ALL Women
        "min_project_cost": 1000000,
        "max_project_cost": 10000000,
        "max_loan_amount": 10000000,
        "beneficiary_interest_rate": 9.25,
        "repayment_years": 7,
        "moratorium_months": 18,
        "channel_partners": ["All Scheduled Commercial Banks", "SIDBI Standup Mitra Portal"],
        "purposes": ["manufacturing", "services", "trading", "agro-allied activities", "greenfield enterprise"],
        "required_documents": ["Caste Certificate (SC/ST) or Female Identity", "Aadhaar Card & PAN", "Detailed Project Report (DPR)", "Land/Premises Documents", "Bank Credit History"],
        "eligibility_rules": ["SC/ST individual OR Female entrepreneur of any category", "Greenfield (first-time) enterprise", "51% shareholding by SC/ST/Woman if non-individual"],
        "source_url": STANDUP_URL,
        "active": True,
    },
    {
        "code": "MUDRA",
        "name": "Pradhan Mantri MUDRA Yojana (PMMY)",
        "provider": "Micro Units Development & Refinance Agency Ltd. (MUDRA)",
        "description": "Collateral-free micro loans up to ₹10 lakh for micro enterprises across Shishu (up to ₹50k), Kishor (₹50k-₹5L), and Tarun (₹5L-₹10L) categories.",
        "beneficiary_category": "General",
        "min_project_cost": None,
        "max_project_cost": 1000000,
        "max_loan_amount": 1000000,
        "beneficiary_interest_rate": 9.5,
        "repayment_years": 5,
        "moratorium_months": 6,
        "channel_partners": ["Public Sector Banks", "Private Banks", "RRBs", "Micro Finance Institutions (MFIs)"],
        "purposes": ["small shop", "vendor", "food stall", "handicrafts", "tailoring", "transport vehicle", "repair workshop", "services"],
        "required_documents": ["MUDRA Application Form", "KYC Documents", "Business Identity/Quotation", "2 Passport Photos"],
        "eligibility_rules": ["Non-farm micro enterprise", "Loan requirement up to ₹10,00,000", "No bank default history"],
        "source_url": MUDRA_URL,
        "active": True,
    },
]

def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        for item in SCHEMES:
            existing = db.query(Scheme).filter(Scheme.code == item["code"]).first()
            if existing:
                for key, value in item.items():
                    setattr(existing, key, value)
            else:
                db.add(Scheme(**item))
        db.commit()
    finally:
        db.close()

if __name__ == "__main__":
    seed()
    print(f"Seed complete. {len(SCHEMES)} schemes loaded into database.")
